import 'package:flutter/material.dart';

import '../../state/aura_scope.dart';

class AuraLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'pt': {
      // Navigation
      'home': 'Início',
      'communicate': 'Mensagens',
      'play': 'Mídia',
      'devices': 'Dispositivos',
      'more': 'Mais',
      'profile': 'Perfil',
      'homeLocation': 'Localização',
      'auraAsk': 'Perguntar para Aura',
      'communicateCall': 'Ligar',
      'communicateMessage': 'Mensagem',
      'communicateChat': 'Chat',
      'communicateDropIn': 'Drop In',
      'communicateAnnouncements': 'Avisos',
      'communicateCalling': 'Chamada',
      'communicateAddContact': 'Novo Contato',
      'communicateEditContact': 'Editar Contato',
      'communicateAddGroup': 'Novo Grupo',
      'deviceLight': 'Luz Principal',
      'deviceAc': 'Ar Condicionado',
      'moreLists': 'Listas e Notas',
      'moreListItems': 'Lista',
      'moreNoteEdit': 'Nota',
      'moreCalendar': 'Calendário',
      'moreCalendarEdit': 'Lembrete',
      'moreAlarms': 'Alarmes e Timers',
      'moreAlarmEdit': 'Editar Alarme',
      'moreAlarmNew': 'Novo Alarme/Timer',
      'moreSkills': 'Skills e Jogos',
      'moreConfig': 'Configurações',
      'moreConfigDevice': 'Dispositivo',
      'moreConfigDeviceSettings': 'Dispositivos',
      'moreConfigDeviceAdd': 'Novo Dispositivo',
      'deviceConfigLight1': 'Configurações do Dispositivo',
      'deviceConfigLight2': 'Configurações do Dispositivo',
      'deviceConfigTv': 'Configurações do Dispositivo',
      'deviceConfigAc': 'Configurações do Dispositivo',
      'deviceConfigEcho': 'Configurações do Dispositivo',
      'moreConfigWifi': 'Rede Wi-Fi',
      'moreConfigBluetooth': 'Bluetooth',
      'moreConfigDisplay': 'Tela e Brilho',
      'moreConfigLanguage': 'Idioma da Aura',
      'moreConfigNotifications': 'Notificações',
      'moreConfigNotificationsRingtone': 'Toque de Notificação',
      'moreConfigAccounts': 'Contas e Perfis',
      'moreConfigAccountsAdd': 'Adicionar Conta',
      'moreActivities': 'Atividades',
      'profileData': 'Dados Pessoais',
      'welcome_title': 'Bem-vindo(a)',
      'welcome_subtitle': 'Entre com e-mail, Apple ou Microsoft.',
      'sign_in': 'Entrar',
      'signing_in': 'Entrando...',
      'recover_password': 'Recuperar senha',
      'accept_terms':
          'Concordo com os Termos de Uso e a Política de Privacidade.',
      'terms': 'Termos de Uso',
      'privacy_policy': 'Política de Privacidade',
      'i_agree': 'Eu concordo com os',
      'and': 'e',
      'email_placeholder': 'seu@email.com',
      'password_placeholder': 'Digite sua senha',
      'login_fields_invalid':
          'Informe um e-mail válido e uma senha com pelo menos 6 caracteres.',
      'or_continue_with': 'ou continue com',
      'active_timer': 'Timer ativo',
      'pause': 'Pausar',
      'reset': 'Zerar',
      'privacy_policy_text':
          'Coletamos apenas os dados necessarios para autenticacao, seguranca, preferencias, contatos autorizados, clima local e operacao dos dispositivos Aura. Dados sensiveis trafegam por HTTPS/TLS, segredos do backend nao ficam no APK e voce pode solicitar acesso, correcao, portabilidade ou exclusao nas configuracoes de privacidade da conta.',
      'terms_text':
          'Ao usar o Aura Mind, voce concorda em manter suas credenciais seguras, usar recursos de casa inteligente de forma licita, respeitar permissoes de dispositivos, contatos e integracoes conectadas, e entender que algumas funcoes dependem de servicos externos como Supabase, Spotify e o backend da Aura.',
      'understood': 'Entendi',
      'social_login_warning':
          'Aceite os termos antes de continuar com login social.',
      'supabase_not_configured':
          'Supabase não configurado. Use --dart-define=SUPABASE_URL=... e --dart-define=SUPABASE_ANON_KEY=... para login real. O botão Entrar usa modo demo.',
      'password_invalid': 'Informe um e-mail válido para recuperar.',
      'password_recovery_sent': 'Link de recuperação enviado para seu e-mail.',
      'login_social_unavailable': 'Login social indisponível: ',
      'tap_to_speak': 'Toque para falar com Aura Mind',
      'listening': 'Ouvindo...',
      'turn_on_lights': 'Ligar luzes',
      'play_jazz': 'Tocar jazz',
      'will_it_rain': 'Vai chover?',
      'ask_by_message': 'Perguntar por mensagem',
      'smart_home': 'Casa Inteligente',
      'see_all': 'Ver tudo',
      'now_playing': 'Tocando Agora',
      'select_call_contact': 'Selecione para quem deseja ligar',
      'select_message_contact': 'Selecione para quem deseja enviar mensagem',
      'contact_name': 'Nome do Contato',
      'contact_phone': 'Número de Telefone',
      'cellphone': 'Celular',
      'aura_echo': 'Aura Echo',
      'save_changes': 'Salvar Alterações',
      'add_contact': 'Adicionar Contato',
      'delete_contact': 'Apagar Contato',
      'selected': 'Selecionado',
      'available': 'Disponível',
      'connected': 'Ativo',
      'app_brightness': 'Brilho do aplicativo',
      'device_brightness': 'Brilho dos aparelhos',
      'adaptive_brightness': 'Brilho adaptativo',
      'app_theme': 'Tema do aplicativo',
      'deliveries_and_alerts': 'Entregas e Alertas',
      'phone_permissions': 'Permissões do celular',
      'connected_status': 'Conectado',
      'profileDataEdit': 'Editar Dados',
      'profileVoice': 'Voz da Aura',
      'profileVoiceLanguage': 'Idioma da Voz',
      'profileVoiceSpeed': 'Velocidade da Voz',
      'profileVoiceWakeWord': 'Palavra de Ativação',
      'profilePrivacy': 'Privacidade',
      'profilePrivacyHistory': 'Histórico de Voz',
      'profilePrivacySkills': 'Permissões',
      'legalTerms': 'Termos de Uso',
      'legalPrivacy': 'Política de Privacidade',
      'skillLogin': 'Conectar Skill',

      // Home
      'greeting_morning': 'Bom dia',
      'greeting_afternoon': 'Boa tarde',
      'greeting_evening': 'Boa noite',
      'current_location': 'Localização',
      'temperature': 'Temperatura',

      // Devices
      'add_device': 'Adicionar Dispositivo',
      'edit_device': 'Editar Dispositivo',
      'delete_device': 'Deletar Dispositivo',
      'light': 'Lâmpada inteligente',
      'tv': 'Smart TV',
      'speaker': 'Alto-falante',
      'ac': 'Ar-condicionado',
      'on': 'Ligado',
      'off': 'Desligado',
      'brightness': 'Brilho',
      'volume': 'Volume',
      'temperature_device': 'Temperatura',

      // Routines
      'routines': 'Rotinas',
      'add_routine': 'Adicionar Rotina',
      'turn_on_at': 'Ligar em',
      'turn_off_at': 'Desligar em',
      'custom_routine': 'Rotina personalizada',

      // Alarms & Timers
      'alarms': 'Alarmes',
      'timers': 'Temporizadores',
      'add_alarm': 'Adicionar Alarme',
      'add_timer': 'Adicionar Temporizador',
      'alarm_time': 'Hora do alarme',
      'repeat': 'Repetir',
      'sound': 'Som',
      'weekdays': 'Dias da semana',
      'everyday': 'Todos os dias',

      // Chat
      'chat': 'Chat',
      'ask_aura': 'Pergunte à Aura',
      'message': 'Mensagem',
      'send': 'Enviar',
      'type_message': 'Digite uma mensagem...',

      // Settings
      'settings': 'Configurações',
      'language': 'Idioma',
      'theme': 'Tema',
      'light_theme': 'Claro',
      'dark_theme': 'Escuro',
      'system_theme': 'Sistema',
      'notifications': 'Notificações',
      'privacy': 'Privacidade',
      'do_not_disturb': 'Não perturbe',
      'notification_tone': 'Tom de notificação',
      'enable_notifications': 'Ativar notificações',
      'enable_push': 'Ativar notificações push',

      // Permissions
      'microphone': 'Microfone',
      'camera': 'Câmera',
      'contacts': 'Contatos',
      'location': 'Localização',
      'bluetooth': 'Bluetooth',
      'wifi': 'Wi-Fi',
      'permission_denied': 'Permissão negada',
      'allow': 'Permitir',
      'deny': 'Negar',

      // Auth
      'login': 'Entrar',
      'logout': 'Sair',
      'email': 'E-mail',
      'password': 'Senha',
      'confirm_password': 'Confirmar senha',
      'forgot_password': 'Esqueceu a senha?',
      'sign_up': 'Criar conta',

      // Common
      'save': 'Salvar',
      'cancel': 'Cancelar',
      'delete': 'Deletar',
      'edit': 'Editar',
      'close': 'Fechar',
      'back': 'Voltar',
      'next': 'Próximo',
      'done': 'Pronto',
      'loading': 'Carregando...',
      'error': 'Erro',
      'success': 'Sucesso',
      'retry': 'Tentar novamente',
      'no_data': 'Sem dados',
    },
    'en': {
      // Navigation
      'home': 'Home',
      'communicate': 'Messages',
      'play': 'Media',
      'devices': 'Devices',
      'more': 'More',
      'profile': 'Profile',
      'homeLocation': 'Location',
      'auraAsk': 'Ask Aura',
      'communicateCall': 'Call',
      'communicateMessage': 'Message',
      'communicateChat': 'Chat',
      'communicateDropIn': 'Drop In',
      'communicateAnnouncements': 'Announcements',
      'communicateCalling': 'Calling',
      'communicateAddContact': 'New Contact',
      'communicateEditContact': 'Edit Contact',
      'communicateAddGroup': 'New Group',
      'deviceLight': 'Main Light',
      'deviceAc': 'Air Conditioner',
      'moreLists': 'Lists and Notes',
      'moreListItems': 'List',
      'moreNoteEdit': 'Note',
      'moreCalendar': 'Calendar',
      'moreCalendarEdit': 'Reminder',
      'moreAlarms': 'Alarms and Timers',
      'moreAlarmEdit': 'Edit Alarm',
      'moreAlarmNew': 'New Alarm/Timer',
      'moreSkills': 'Skills and Games',
      'moreConfig': 'Settings',
      'moreConfigDevice': 'Device',
      'moreConfigDeviceSettings': 'Devices',
      'moreConfigDeviceAdd': 'New Device',
      'deviceConfigLight1': 'Device Settings',
      'deviceConfigLight2': 'Device Settings',
      'deviceConfigTv': 'Device Settings',
      'deviceConfigAc': 'Device Settings',
      'deviceConfigEcho': 'Device Settings',
      'moreConfigWifi': 'Wi-Fi Network',
      'moreConfigBluetooth': 'Bluetooth',
      'moreConfigDisplay': 'Display and Brightness',
      'moreConfigLanguage': 'Aura Language',
      'moreConfigNotifications': 'Notifications',
      'moreConfigNotificationsRingtone': 'Notification Ringtone',
      'moreConfigAccounts': 'Accounts and Profiles',
      'moreConfigAccountsAdd': 'Add Account',
      'moreActivities': 'Activities',
      'profileData': 'Personal Data',
      'welcome_title': 'Welcome',
      'welcome_subtitle': 'Sign in with email, Apple, or Microsoft.',
      'sign_in': 'Log in',
      'signing_in': 'Signing in...',
      'recover_password': 'Recover password',
      'accept_terms': 'I agree with the Terms of Use and Privacy Policy.',
      'terms': 'Terms of Use',
      'privacy_policy': 'Privacy Policy',
      'i_agree': 'I agree with the',
      'and': 'and',
      'email_placeholder': 'your@email.com',
      'password_placeholder': 'Enter your password',
      'login_fields_invalid':
          'Enter a valid email and a password with at least 6 characters.',
      'or_continue_with': 'or continue with',
      'active_timer': 'Active timer',
      'pause': 'Pause',
      'reset': 'Reset',
      'privacy_policy_text':
          'We collect only the data needed for authentication, security, preferences, authorized contacts, local weather and Aura device operation. Sensitive data uses HTTPS/TLS in transit, backend secrets are not stored in the APK, and you may request access, correction, portability or deletion in account privacy settings.',
      'terms_text':
          'By using Aura Mind, you agree to keep your credentials secure, use smart home features lawfully, respect device, contact and integration permissions, and understand that some features depend on external services such as Supabase, Spotify and the Aura backend.',
      'understood': 'Got it',
      'social_login_warning':
          'Accept the terms before continuing with social login.',
      'supabase_not_configured':
          'Supabase not configured. Use --dart-define=SUPABASE_URL=... and --dart-define=SUPABASE_ANON_KEY=... for real login. Login button uses demo mode.',
      'password_invalid': 'Enter a valid email to recover.',
      'password_recovery_sent': 'Password recovery link sent to your email.',
      'login_social_unavailable': 'Social login unavailable: ',
      'tap_to_speak': 'Tap to speak with Aura Mind',
      'listening': 'Listening...',
      'turn_on_lights': 'Turn on lights',
      'play_jazz': 'Play jazz',
      'will_it_rain': 'Will it rain?',
      'ask_by_message': 'Ask by message',
      'smart_home': 'Smart Home',
      'see_all': 'See all',
      'now_playing': 'Now Playing',
      'select_call_contact': 'Select who you want to call',
      'select_message_contact': 'Select who you want to message',
      'contact_name': 'Contact Name',
      'contact_phone': 'Phone Number',
      'cellphone': 'Cellphone',
      'aura_echo': 'Aura Echo',
      'save_changes': 'Save Changes',
      'add_contact': 'Add Contact',
      'delete_contact': 'Delete Contact',
      'selected': 'Selected',
      'available': 'Available',
      'connected': 'Connected',
      'app_brightness': 'App brightness',
      'device_brightness': 'Device brightness',
      'adaptive_brightness': 'Adaptive brightness',
      'app_theme': 'App theme',
      'deliveries_and_alerts': 'Deliveries and alerts',
      'phone_permissions': 'Phone permissions',
      'connected_status': 'Connected',
      'profileDataEdit': 'Edit Data',
      'profileVoice': 'Aura Voice',
      'profileVoiceLanguage': 'Voice Language',
      'profileVoiceSpeed': 'Voice Speed',
      'profileVoiceWakeWord': 'Wake Word',
      'profilePrivacy': 'Privacy',
      'profilePrivacyHistory': 'Voice History',
      'profilePrivacySkills': 'Permissions',
      'legalTerms': 'Terms of Use',
      'legalPrivacy': 'Privacy Policy',
      'skillLogin': 'Connect Skill',

      // Home
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'current_location':
          'Location', // <--- Alterado de 'location' para 'current_location'
      'temperature': 'Temperature',

      // Devices
      'add_device': 'Add Device',
      'edit_device': 'Edit Device',
      'delete_device': 'Delete Device',
      'light': 'Smart Light',
      'tv': 'Smart TV',
      'speaker': 'Speaker',
      'ac': 'Air Conditioner',
      'on': 'On',
      'off': 'Off',
      'brightness': 'Brightness',
      'volume': 'Volume',
      'temperature_device': 'Temperature',

      // Routines
      'routines': 'Routines',
      'add_routine': 'Add Routine',
      'turn_on_at': 'Turn on at',
      'turn_off_at': 'Turn off at',
      'custom_routine': 'Custom routine',

      // Alarms & Timers
      'alarms': 'Alarms',
      'timers': 'Timers',
      'add_alarm': 'Add Alarm',
      'add_timer': 'Add Timer',
      'alarm_time': 'Alarm time',
      'repeat': 'Repeat',
      'sound': 'Sound',
      'weekdays': 'Weekdays',
      'everyday': 'Every day',

      // Chat
      'chat': 'Chat',
      'ask_aura': 'Ask Aura',
      'message': 'Message',
      'send': 'Send',
      'type_message': 'Type a message...',

      // Settings
      'settings': 'Settings',
      'language': 'Language',
      'theme': 'Theme',
      'light_theme': 'Light',
      'dark_theme': 'Dark',
      'system_theme': 'System',
      'notifications': 'Notifications',
      'privacy': 'Privacy',
      'do_not_disturb': 'Do Not Disturb',
      'notification_tone': 'Notification tone',
      'enable_notifications': 'Enable notifications',
      'enable_push': 'Enable push notifications',

      // Permissions
      'microphone': 'Microphone',
      'camera': 'Camera',
      'contacts': 'Contacts',
      'location':
          'Location', // <--- A chave 'location' original das permissões continua aqui
      'bluetooth': 'Bluetooth',
      'wifi': 'Wi-Fi',
      'permission_denied': 'Permission denied',
      'allow': 'Allow',
      'deny': 'Deny',

      // Auth
      'login': 'Log in',
      'logout': 'Log out',
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm password',
      'forgot_password': 'Forgot password?',
      'sign_up': 'Sign up',

      // Common
      'save': 'Save',
      'cancel': 'Cancel',
      'delete': 'Delete',
      'edit': 'Edit',
      'close': 'Close',
      'back': 'Back',
      'next': 'Next',
      'done': 'Done',
      'loading': 'Loading...',
      'error': 'Error',
      'success': 'Success',
      'retry': 'Retry',
      'no_data': 'No data',
    },
    'es': {
      // Navigation
      'home': 'Inicio',
      'communicate': 'Mensajes',
      'play': 'Medios',
      'devices': 'Dispositivos',
      'more': 'Más',
      'profile': 'Perfil',
      'homeLocation': 'Ubicación',
      'auraAsk': 'Preguntar a Aura',
      'communicateCall': 'Llamar',
      'communicateMessage': 'Mensaje',
      'communicateChat': 'Chat',
      'communicateDropIn': 'Drop In',
      'communicateAnnouncements': 'Avisos',
      'communicateCalling': 'Llamada',
      'communicateAddContact': 'Nuevo Contacto',
      'communicateEditContact': 'Editar Contacto',
      'communicateAddGroup': 'Nuevo Grupo',
      'deviceLight': 'Luz Principal',
      'deviceAc': 'Aire Acondicionado',
      'moreLists': 'Listas y Notas',
      'moreListItems': 'Lista',
      'moreNoteEdit': 'Nota',
      'moreCalendar': 'Calendario',
      'moreCalendarEdit': 'Recordatorio',
      'moreAlarms': 'Alarmas y Temporizadores',
      'moreAlarmEdit': 'Editar Alarma',
      'moreAlarmNew': 'Nueva Alarma/Temporizador',
      'moreSkills': 'Skills y Juegos',
      'moreConfig': 'Configuración',
      'moreConfigDevice': 'Dispositivo',
      'moreConfigDeviceSettings': 'Dispositivos',
      'moreConfigDeviceAdd': 'Nuevo Dispositivo',
      'deviceConfigLight1': 'Configuración del Dispositivo',
      'deviceConfigLight2': 'Configuración del Dispositivo',
      'deviceConfigTv': 'Configuración del Dispositivo',
      'deviceConfigAc': 'Configuración del Dispositivo',
      'deviceConfigEcho': 'Configuración del Dispositivo',
      'moreConfigWifi': 'Red Wi-Fi',
      'moreConfigBluetooth': 'Bluetooth',
      'moreConfigDisplay': 'Pantalla y Brillo',
      'moreConfigLanguage': 'Idioma de Aura',
      'moreConfigNotifications': 'Notificaciones',
      'moreConfigNotificationsRingtone': 'Tono de Notificación',
      'moreConfigAccounts': 'Cuentas y Perfiles',
      'moreConfigAccountsAdd': 'Agregar Cuenta',
      'moreActivities': 'Actividades',
      'profileData': 'Datos Personales',
      'welcome_title': 'Bienvenido(a)',
      'welcome_subtitle': 'Inicia sesión con correo, Apple o Microsoft.',
      'sign_in': 'Iniciar sesión',
      'signing_in': 'Iniciando...',
      'recover_password': 'Recuperar contraseña',
      'accept_terms':
          'Estoy de acuerdo con los Términos de Uso y la Política de Privacidad.',
      'terms': 'Términos de Uso',
      'privacy_policy': 'Política de Privacidad',
      'i_agree': 'Estoy de acuerdo con los',
      'and': 'y',
      'email_placeholder': 'tu@email.com',
      'password_placeholder': 'Ingresa tu contraseña',
      'login_fields_invalid':
          'Ingresa un correo válido y una contraseña de al menos 6 caracteres.',
      'or_continue_with': 'o continúa con',
      'active_timer': 'Temporizador activo',
      'pause': 'Pausar',
      'reset': 'Restablecer',
      'privacy_policy_text':
          'Recopilamos solo los datos necesarios para autenticacion, seguridad, preferencias, contactos autorizados, clima local y funcionamiento de dispositivos Aura. Los datos sensibles viajan por HTTPS/TLS, los secretos del backend no quedan en el APK y puedes solicitar acceso, correccion, portabilidad o eliminacion en privacidad de la cuenta.',
      'terms_text':
          'Al usar Aura Mind, aceptas mantener tus credenciales seguras, usar funciones de hogar inteligente de forma licita, respetar permisos de dispositivos, contactos e integraciones, y entender que algunas funciones dependen de Supabase, Spotify y el backend de Aura.',
      'understood': 'Entendido',
      'social_login_warning':
          'Acepta los términos antes de continuar con el inicio de sesión social.',
      'supabase_not_configured':
          'Supabase no configurado. Usa --dart-define=SUPABASE_URL=... y --dart-define=SUPABASE_ANON_KEY=... para iniciar sesión real. El botón de inicio de sesión usa modo demo.',
      'password_invalid': 'Ingrese un correo válido para recuperar.',
      'password_recovery_sent':
          'Enviado un enlace de recuperación a tu correo.',
      'login_social_unavailable': 'Inicio social no disponible: ',
      'tap_to_speak': 'Toca para hablar con Aura Mind',
      'listening': 'Escuchando...',
      'turn_on_lights': 'Encender luces',
      'play_jazz': 'Reproducir jazz',
      'will_it_rain': '¿Lloverá?',
      'ask_by_message': 'Preguntar por mensaje',
      'smart_home': 'Casa Inteligente',
      'see_all': 'Ver todo',
      'now_playing': 'Reproduciendo Ahora',
      'select_call_contact': 'Selecciona a quién quieres llamar',
      'select_message_contact': 'Selecciona a quién quieres enviar mensaje',
      'contact_name': 'Nombre de Contacto',
      'contact_phone': 'Número de Teléfono',
      'cellphone': 'Celular',
      'aura_echo': 'Aura Echo',
      'save_changes': 'Guardar Cambios',
      'add_contact': 'Agregar Contacto',
      'delete_contact': 'Eliminar Contacto',
      'selected': 'Seleccionado',
      'available': 'Disponible',
      'connected': 'Conectado',
      'app_brightness': 'Brillo de la app',
      'device_brightness': 'Brillo de los dispositivos',
      'adaptive_brightness': 'Brillo adaptativo',
      'app_theme': 'Tema de la app',
      'deliveries_and_alerts': 'Entregas y alertas',
      'phone_permissions': 'Permisos del teléfono',
      'connected_status': 'Conectado',
      'profileDataEdit': 'Editar Datos',
      'profileVoice': 'Voz de Aura',
      'profileVoiceLanguage': 'Idioma de la Voz',
      'profileVoiceSpeed': 'Velocidad de la Voz',
      'profileVoiceWakeWord': 'Palabra de Activación',
      'profilePrivacy': 'Privacidad',
      'profilePrivacyHistory': 'Historial de Voz',
      'profilePrivacySkills': 'Permisos',
      'legalTerms': 'Términos de Uso',
      'legalPrivacy': 'Política de Privacidad',
      'skillLogin': 'Conectar Skill',

      // Home
      'greeting_morning': 'Buenos días',
      'greeting_afternoon': 'Buenas tardes',
      'greeting_evening': 'Buenas noches',
      'current_location':
          'Ubicación', // <--- Alterado de 'location' para 'current_location'
      'temperature': 'Temperatura',

      // Devices
      'add_device': 'Agregar Dispositivo',
      'edit_device': 'Editar Dispositivo',
      'delete_device': 'Eliminar Dispositivo',
      'light': 'Luz Inteligente',
      'tv': 'Smart TV',
      'speaker': 'Altavoz',
      'ac': 'Aire Acondicionado',
      'on': 'Encendido',
      'off': 'Apagado',
      'brightness': 'Brillo',
      'volume': 'Volumen',
      'temperature_device': 'Temperatura',

      // Routines
      'routines': 'Rutinas',
      'add_routine': 'Agregar Rutina',
      'turn_on_at': 'Encender en',
      'turn_off_at': 'Apagar en',
      'custom_routine': 'Rutina personalizada',

      // Alarms & Timers
      'alarms': 'Alarmas',
      'timers': 'Temporizadores',
      'add_alarm': 'Agregar Alarma',
      'add_timer': 'Agregar Temporizador',
      'alarm_time': 'Hora de la alarma',
      'repeat': 'Repetir',
      'sound': 'Sonido',
      'weekdays': 'Días de la semana',
      'everyday': 'Todos los días',

      // Chat
      'chat': 'Chat',
      'ask_aura': 'Preguntar a Aura',
      'message': 'Mensaje',
      'send': 'Enviar',
      'type_message': 'Escriba un mensaje...',

      // Settings
      'settings': 'Configuración',
      'language': 'Idioma',
      'theme': 'Tema',
      'light_theme': 'Claro',
      'dark_theme': 'Oscuro',
      'system_theme': 'Sistema',
      'notifications': 'Notificaciones',
      'privacy': 'Privacidad',
      'do_not_disturb': 'No molestar',
      'notification_tone': 'Tono de notificación',
      'enable_notifications': 'Habilitar notificaciones',
      'enable_push': 'Habilitar notificaciones push',

      // Permissions
      'microphone': 'Micrófono',
      'camera': 'Cámara',
      'contacts': 'Contactos',
      'location':
          'Ubicación', // <--- A chave 'location' original das permissões continua aqui
      'bluetooth': 'Bluetooth',
      'wifi': 'Wi-Fi',
      'permission_denied': 'Permiso denegado',
      'allow': 'Permitir',
      'deny': 'Denegar',

      // Auth
      'login': 'Iniciar sesión',
      'logout': 'Cerrar sesión',
      'email': 'Correo electrónico',
      'password': 'Contraseña',
      'confirm_password': 'Confirmar contraseña',
      'forgot_password': '¿Olvidó su contraseña?',
      'sign_up': 'Crear cuenta',

      // Common
      'save': 'Guardar',
      'cancel': 'Cancelar',
      'delete': 'Eliminar',
      'edit': 'Editar',
      'close': 'Cerrar',
      'back': 'Atrás',
      'next': 'Siguiente',
      'done': 'Listo',
      'loading': 'Cargando...',
      'error': 'Error',
      'success': 'Éxito',
      'retry': 'Reintentar',
      'no_data': 'Sin datos',
    },
  };

  static String translate(String key, {String? lang}) {
    final language = lang ?? 'pt';
    return _translations[language]?[key] ?? _translations['pt']?[key] ?? key;
  }

  static List<String> get supportedLanguages => _translations.keys.toList();

  static String languageName(String code) {
    return switch (code) {
      'pt' => 'Português (Brasil)',
      'en' => 'English',
      'es' => 'Español',
      _ => code,
    };
  }
}

extension LocalizationExtension on BuildContext {
  String tr(String key) {
    final language = AuraScope.maybeOf(this)?.lang ?? 'pt';
    return AuraLocalizations.translate(key, lang: language);
  }
}
